### PR TITLE
Move resource tests to their own thing

### PR DESCRIPTION
**Pull request by smith**
* Create a test cookbook to test the `component_runit_supervisor` resource directly rather than through the runit cookbook.
* Add a matcher to use in the cookbook instead.

/cc @chef/visual-interaction @chef/lob @jtimberman

### CODE REVIEW

**Comment by raskchanky** [comment]
@smith I ran `chef exec rspec` on this and got 8 failures, all related to stubbing out a grep command, which looks like this:



Is there a better way to test this?

**Comment by smith** [comment]
@raskchanky this may have broken on a rebase. I'll check it out and push commits. That's the right command to run.

**Comment by raskchanky** [comment]
Modulo test failures, and with the caveat that a lot of what's happening here is a bit over my head in terms of chef knowledge, this looks fine.  :+1:

**Comment by smith** [comment]
Should work now.

**Comment by raskchanky** [comment]
Yup looks good :shipit:

**Pull request merged**
