### PR TITLE
Ubuntu (upstart) / Debian (sysvinit) split

### PR DESCRIPTION
**Pull request by gplessis**
Even is Chef Server 12 is not officially supported on Debian, the Ubuntu 11.04 packages (glibc compatible) work perfectly after applying this PR's changes.

I just introduced an additional test on `platform` to split the Ubuntu and Debian cases. Of course, some more check could be added once Debian "Jessie" (with systemd) is out.

And yes, it's possible to switch from sysV to Upstart on Debian Wheezy. But while sysV is the default and bullet-proof on any environment, it's definitely not the case for Upstart. For example, switching to it on [the official EC2 AMIs from Debian](https://wiki.debian.org/Cloud/AmazonEC2Image/Wheezy) prevents the instances to be back after a reboot. On a bare-metal install, Upstart works but some core services (resolvconf, for example) don't.

FYI, the same discussion happened for Chef 11 : https://github.com/opscode/omnibus-chef-server/pull/70

### CODE REVIEW

**Comment by lebrinkma** [comment]
I would also like to see this applied to be able to run Chef Server 12 on Debian 7 although it's not officially supported.

@gplessis I think the PR has to be updated to apply to latest master.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @gplessis

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by gplessis** [comment]
The PR has been updated and is now ready to be merged. I also signed the CLA as an individual.

**Comment by stanhu** [comment]
The plot thickens: Ubuntu 15.04 has switched the default from upstart to systemd. :)

**Comment by lebrinkma** [comment]
@stanhu The code checks for systemd first, so this should work fine.

Any chances of getting this merged?

**Comment by chewi** [comment]
@lebrinkma, you're right except that I set the path to `/usr/lib/systemd/system/#{unit_name}` and I now realise that for Debian, this needs to be `/lib/systemd/system/#{unit_name}`. This works for RHEL too as `/lib` is just a symlink to `/usr/lib`. I would file a pull request myself but I don't have time to test it. You guys are testing Debian/Ubuntu anyway so…

**Comment by smith** [comment]
#33 should replace this. Closing. Please add any further comments on the new PR and let me know if anything needs to be done differently there. Thanks!

**Pull request closed without merging**
